# general settings
name: SFIS_light_SRx4
model_type: SFISModel
scale: 4
num_gpu: 1
manual_seed: 0
# find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/DF2K/HR
    dataroot_lq: /root/autodl-tmp/DF2K/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 24
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/TestDataSR/HR/Set5/x4
    dataroot_lq: /root/autodl-tmp/TestDataSR/LR/LRBI/Set5/x4
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/TestDataSR/HR/Set14/x4
    dataroot_lq: /root/autodl-tmp/TestDataSR/LR/LRBI/Set14/x4
    io_backend:
      type: disk

  val_3:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/TestDataSR/HR/B100/x4
    dataroot_lq: /root/autodl-tmp/TestDataSR/LR/LRBI/B100/x4
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/TestDataSR/HR/Urban100/x4
    dataroot_lq: /root/autodl-tmp/TestDataSR/LR/LRBI/Urban100/x4
    io_backend:
      type: disk

  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/TestDataSR/HR/Manga109/x4
    dataroot_lq: /root/autodl-tmp/TestDataSR/LR/LRBI/Manga109/x4
    io_backend:
      type: disk

# network structures
network_g:
  type: SFIS
  upscale: 4
  in_chans: 3
  img_size: 64
  embed_dim: 48
  depths: [6, 6, 6, 6]
  num_heads: [4, 4, 4, 4]
  window_size: 16
  category_size: 128
  num_tokens: 64
  reducted_dim: 8
  convffn_kernel_size: 7
  img_range: 1.
  mlp_ratio: 1
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'
  use_checkpoint: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.9]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000, 490000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: 20000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: yes

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: yes

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
